### ISSUE TITLE
--heartbeat flag not present in cfn-push-stats

### ISSUE THREAD

**Issue by sdake** [sdake/heat-jeos#14]
Angus,

I think you missed a commit on cfn-push-stats

[root@wikidatabase bin]# ./cfn-push-stats --heartbeat --watch HeartbeatFailureAlarm
WARNING [2012-08-06 12:34:41,749] psutil not available. If you want process and memory statistics, you need to install it.
usage: cfn-push-stats [-h] [-v] [--service-failure] [--mem-util] [--mem-used]
                      [--mem-avail] [--swap-util] [--swap-used]
                      [--disk-space-util] [--disk-space-used]
                      [--disk-space-avail] [--memory-units MEMORY_UNITS]
                      [--disk-units DISK_UNITS] [--disk-path DISK_PATH]
                      [--haproxy] --watch WATCH
cfn-push-stats: error: unrecognized arguments: --heartbeat

IHA template doesn't work as a result

**Comment by asalkeld** [comment]
Sorry, that's dumb. Pushed now.
