### ISSUE TITLE
cfn-hup does not work

### ISSUE THREAD

**Issue by nakamichi** [sdake/heat-jeos#43]
I tried AutoScalingMultiAZSample.template. Then first, F17 LB_instance is started, but cfn-hup does not work. So HAProxy is not set.
I confirm LB_instance's credential file(/etc/cfn/cfn-credential) is blank(AWSAccessKeyId and AWSSecretKey are not set). Then boto client fails authorized.

My environment is baed on OpenStack Folsom(2012.2.3).
heat is commit:44ea0380041fd353a22f3d99a266d9cd3399ea5c.
heat-jeos is commit:88e0f4154d0539757085cb14de0e2f1bd864ba23

**Comment by hardys** [comment]
This is not a heat-jeos bug, you've identified the problem as being lack of credentials in /etc/cfn/cfn-credentials, this is a bug in heat in the nested template for the LoadBalancer resource, not a bug in cfn-hup.

There is a review in-progress which will fix this issue:
https://review.openstack.org/#/c/21794/

**Comment by nakamichi** [comment]
I see. Thanks for telling me.

**Comment by hardys** [comment]
No problem - if you still have problems after the review above gets merged, pleased feel free to come to #heat on Freenode where we can help you :)
