### ISSUE TITLE
Make the commands in the tdl more readable

### ISSUE THREAD

**Issue by asalkeld** [sdake/heat-jeos#5]
```
yum -y update --skip-broken;yum -y install yum-plugin-fastestmirror;yum -y update;/usr/sbin/useradd ec2-user;echo -e 'ec2-user\tALL=(ALL)\tNOPASSWD: ALL' >> /etc/sudoers;yum -y install cloud-init;cat >> /etc/rc.d/rc.local &lt;&lt; EOF;chmod +x /etc/rc.d/rc.local;chmod +x /opt/aws/bin/cfn-*
#!/bin/bash
setenforce 0
EOF
```

Assuming that still does as advertised

```
yum -y update --skip-broken
yum -y install yum-plugin-fastestmirror
yum -y update
/usr/sbin/useradd ec2-user
echo -e 'ec2-user\tALL=(ALL)\tNOPASSWD: ALL' >> /etc/sudoers
yum -y install cloud-init
setenforce 0
sed -i "s/SELINUX=enforcing/SELINUX=permissive/" /etc/sysconfig/selinux
chmod +x /opt/aws/bin/cfn-*
```

**Comment by sdake** [comment]
changing selinux to permissive in the running commands I think doesn't work.  Oz changes to permissive during install or customization then retores the old selinux config file.  I could be wrong on this point, or it could have changed - worth investigation.

This is why there is a rc.local script to do this.

Also I believe oz needs a CR between each of these elements or it doesn't work properly.

If this change is made, make sure to test all the images again.

Thanks
-steve
