### ISSUE TITLE
files section creates an error on the vm (No such file or directory: ''")

### ISSUE THREAD

**Issue by asalkeld** [sdake/heat-jeos#8]
It's trying to create a dir with name ""

Jul  2 22:20:12 localhost cloud-init-cfg[909]: ERROR [2012-07-02 22:20:12,827] [Errno 2] No such file or directory: ''"
Jul  2 22:20:12 localhost cloud-init-cfg[909]: Traceback (most recent call last):
Jul  2 22:20:12 localhost cloud-init-cfg[909]: File "/opt/aws/bin/cfn_helper.py", line 521, in apply_files
Jul  2 22:20:12 localhost cloud-init-cfg[909]: os.makedirs(os.path.dirname(dest))
Jul  2 22:20:12 localhost cloud-init-cfg[909]: File "/usr/lib64/python2.7/os.py", line 157, in makedirs
Jul  2 22:20:12 localhost cloud-init-cfg[909]: mkdir(name, mode)

**Comment by zaneb** [comment]
@asalkeld you're giving up just like that? :laughing:
